apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: REPO_URL
      type: string
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(params.REPO_URL) --depth 1 /workspace/source
    - name: npm-install
      image: node
      command:
        - /bin/sh
        - -c
      args: 
        - npm install
      workingDir: /workspace/source
    - name: npm-test
      image: node
      command:
        - /bin/sh
        - -c
      args: 
        - npm test
      workingDir: /workspace/source