apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: REPO_URL
      type: string
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(params.REPO_URL) --depth 1 /workspace/source
    - name: kubectl-apply
      image: lachlanevenson/k8s-kubectl
      script: |
        kubectl apply -f /workspace/source/tekton/k8s/nginx-deployment.yml
    - name: kubectl-image
      image: lachlanevenson/k8s-kubectl
      script: |
        kubectl set image deployment/nginx-deployment nginx=$(params.IMAGE) -n=$(params.NAMESPACE)
